"""Monday-morning security brief export (Markdown)."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def build_incident_brief(
    *,
    user_email: str,
    analysis: dict[str, Any] | None,
    plan: dict[str, Any] | None,
    decisions: list[dict[str, Any]],
    receipt: dict[str, Any] | None,
    session_id: str = "",
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# SecBrief — Security Incident Brief",
        "",
        f"**Prepared:** {now}  ",
        f"**Owner:** {user_email}  ",
    ]
    if session_id:
        lines.append(f"**Session ID:** `{session_id}`  ")
    lines.extend(["", "---", ""])

    if analysis:
        lines.extend(
            [
                "## Executive summary",
                "",
                f"**{analysis.get('title', 'Security finding')}**",
                "",
                f"- **Severity:** {analysis.get('severity', 'Unknown')}",
                f"- **Risk score:** {analysis.get('risk_score', '?')}/10",
                "",
                analysis.get("summary", ""),
                "",
            ]
        )
        if analysis.get("what_to_do"):
            lines.append("### Recommended actions")
            for i, step in enumerate(analysis["what_to_do"][:8], 1):
                lines.append(f"{i}. {step}")
            lines.append("")

    if plan:
        lines.extend(["## Policy-checked remediation plan", "", f"**Goal:** {plan.get('goal', '')}", ""])
        for i, s in enumerate(plan.get("steps", []), 1):
            lines.append(f"{i}. `{s.get('action')}` — {s.get('description', '')}")
        lines.append("")

    if decisions:
        lines.extend(["## ArmorIQ enforcement log", "", "| Step | Status | Notes |", "|------|--------|-------|"])
        for d in decisions:
            status = d.get("status", "?").upper()
            flag = " ⚠️ not in signed plan" if d.get("in_signed_plan") is False else ""
            lines.append(
                f"| `{d.get('action')}` | **{status}** | {d.get('message', '')}{flag} |"
            )
        lines.append("")

    if receipt and receipt.get("plan_hash"):
        lines.extend(
            [
                "## Cryptographic intent receipt",
                "",
                f"- **Plan hash:** `{receipt.get('plan_hash')}`",
                f"- **Intent reference:** `{receipt.get('token_id', 'n/a')}`",
                f"- **Steps in plan:** {receipt.get('total_steps', 0)}",
                f"- **Merkle proofs:** {receipt.get('step_proofs_count', 0)}",
                f"- **Live ArmorIQ:** {'yes' if receipt.get('armoriq_live') else 'demo mode'}",
                "",
                "_Audit trail: [platform.armoriq.ai](https://platform.armoriq.ai)_",
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            "*Generated by SecBrief — explain the risk, enforce the fix. "
            "Not a generic copilot; every remediation step is intent-bound.*",
        ]
    )
    return "\n".join(lines)
